version: "3"
services: 
    caremall:
        build: .
        ports: 
            - "80:80"
        volumes: 
            - ../caremall-eccube:/var/www/html
        networks:
            caremall_net:
    mysql:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: caremall # default database
        ports:
            - 3306:3306
        networks:
            caremall_net:
                aliases: 
                    - mysql #local domain
networks:
    caremall_net: